[ERROR] 2019-07-01 13:01:52,192 | /home/ilhmndn/frappe-training/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: startswith first arg must be str or a tuple of str, not bytes
Traceback (most recent call last):
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/__init__.py", line 1019, in call
    return fn(*args, **newargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 848, in submit
    self._submit()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 908, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/warehouse/warehouse/warehouse_management_system/doctype/request_pesanan_barang/request_pesanan_barang.py", line 13, in on_submit
    self.on_approve()
  File "/home/ilhmndn/frappe-training/apps/warehouse/warehouse/warehouse_management_system/doctype/request_pesanan_barang/request_pesanan_barang.py", line 22, in on_approve
    for i in self.request_line_barang:
AttributeError: 'RequestPesananBarang' object has no attribute 'request_line_pesanan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/utils/error.py", line 131, in get_snapshot
    if type(value)==str and value.startswith(b"u'"):
TypeError: startswith first arg must be str or a tuple of str, not bytes
[ERROR] 2019-07-01 13:02:09,407 | /home/ilhmndn/frappe-training/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: startswith first arg must be str or a tuple of str, not bytes
Traceback (most recent call last):
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/__init__.py", line 1019, in call
    return fn(*args, **newargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 848, in submit
    self._submit()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 908, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/warehouse/warehouse/warehouse_management_system/doctype/request_pesanan_barang/request_pesanan_barang.py", line 13, in on_submit
    self.on_approve()
  File "/home/ilhmndn/frappe-training/apps/warehouse/warehouse/warehouse_management_system/doctype/request_pesanan_barang/request_pesanan_barang.py", line 22, in on_approve
    for i in self.request_line_barang:
AttributeError: 'RequestPesananBarang' object has no attribute 'request_line_pesanan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/utils/error.py", line 131, in get_snapshot
    if type(value)==str and value.startswith(b"u'"):
TypeError: startswith first arg must be str or a tuple of str, not bytes
[ERROR] 2019-07-01 13:03:04,306 | /home/ilhmndn/frappe-training/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: startswith first arg must be str or a tuple of str, not bytes
Traceback (most recent call last):
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/__init__.py", line 1019, in call
    return fn(*args, **newargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 848, in submit
    self._submit()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 908, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ilhmndn/frappe-training/apps/warehouse/warehouse/warehouse_management_system/doctype/request_pesanan_barang/request_pesanan_barang.py", line 13, in on_submit
    self.on_approve()
  File "/home/ilhmndn/frappe-training/apps/warehouse/warehouse/warehouse_management_system/doctype/request_pesanan_barang/request_pesanan_barang.py", line 22, in on_approve
    for i in self.request_line_barang:
AttributeError: 'RequestPesananBarang' object has no attribute 'request_line_pesanan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ilhmndn/frappe-training/apps/frappe/frappe/utils/error.py", line 131, in get_snapshot
    if type(value)==str and value.startswith(b"u'"):
TypeError: startswith first arg must be str or a tuple of str, not bytes
